name: ai_chatbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  shared_preferences: ^2.1.2
  jwt_decoder: ^2.0.1
  dio: ^5.2.1+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.0.8
  camera: ^0.11.0+2
  lottie: ^3.1.3
  google_ml_kit: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
